---

- name: Copy the docker installables and deploy the docker-compose application 
  hosts: ec2
  tasks:
    - name: Copy the docker and application setup script in the server
      get_url:
        url: https://raw.githubusercontent.com/Arvind-Jagirala/ITGlue_Repo/main/dockersetup.sh
        dest: /opt/dockersetup.sh
        owner: root
        group: root
        mode: 0755

    - name: Run docker in the server
      shell: /opt/dockersetup.sh

    - name: Run  application in the server
      command: docker-compose up --build 
      args:
        chdir: /root/ITGlue_Repo
